In [ ]:
# In this notebook, we will cover the fundamentals of tensor using TensorFlow

# More specifically, we'll cover Intro to Tensors, getting info from tensors, maniplating tensors, tensors & NumPy, using @tf.function
# (speeding up regular python functions), using GPUs or TPUs with TF 

## Intro to tensors

# Import TensorFlow
import tensorflow as tf
print(tf.__version__)


In [2]:
# Creating tensors with tf.constant()
scalar = tf.constant(7) # creates a constant tensor from tensor-like constant
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# check the number of dimensions of a tensor (ndim stands for num of dims)
scalar.ndim


0

In [5]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [6]:
# Check dim of vector, note shape has one element compared to a scalar having 0
vector.ndim

1

In [7]:
# create a matrix (more than one dim)
matrix = tf.constant([[10,7],
                      [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [8]:
matrix.ndim

2

In [13]:
# Create another matrix 
another_matrix = tf.constant([[10.,7.],
                              [3.,2.],
                              [8.,9.]], dtype=tf.float16) # specify dtype param
# the higher the number of precision, the more exact the numbers are stored.
# 16 is lower than 32 so storing the tensor is taking up less space
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [14]:
# What's the dim num for another_matrix
another_matrix.ndim

2

In [ ]:
# Let's create a tensor for higher dims
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                       [[7,8,9],
                       [10,11,12]],
                       [[13,14,15],
                       [16,17,18]]])
tensor               

In [16]:
tensor.ndim

3

# What we've created so far:
 * Scalar: single num
 * Vector: num with direction
 * Matrix: 2D array of number
 * Tensor: n-dim array of numbers (n can be any num)

Creating Tensors with `tf.Variable()

In [22]:
# Create the same tensor with tf.variable as above
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [23]:
# Lets try and change one of the elements in our changeable tensor
changeable_tensor[0] = 7
changeable_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [24]:
# How about we try .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7])>

In [26]:
# Lets try to change the unchangable tensor
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [27]:
# Note the name tf.Variable vs tf.constant - one is variable and one is constant

### Creating random tensors

Random tensors are tensors of some arbitrary size which contain random numbers
Why? We can initialize the numerical coding with random weights, which will then see example and update representation outputs. see 1:25 of video for visual

# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(7) # set seed for reproducibility
random_1 = random_1.normal(shape=(3,2)) # Creating 3x2 matrix following normal model
random_2 = tf.random.Generator.from_seed(7)
random_2 = random_2.normal(shape=(3,2))
# Are they equal?
random_1, random_2, random_1==random_2

### What if we wanted to shuffle the order of how the elements appear within the tensor? 
Why? The order in which the images are shown is important. We don't want it to only think about cars and not trucks. You can mix up all the pictures in the folder so that it gets used to cars and trucks and learn both at the same time

In [36]:
# Shuffle a tensor (valuable for shuffling data so the inherent order doesn't affect learning)
not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [2,5]])
# Tensors can be shuffled with tf.random.shuffle()
tf.random.shuffle(not_shuffled) # only shuffled along first dimension (in this case, row)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7],
       [ 2,  5]])>

In [92]:
# tf.random.shuffle(not_shuffled) run this multiple times! It will be a different order

tf.random.set_seed(42) # global level seed
tf.random.shuffle(not_shuffled,seed=42) # operation level seed

# These two lines will force the same order, if we want our shuffled tensors to be in the same order, use both global and operation level
# These are good for reproducable data!!

# https://www.tensorflow.org/api_docs/python/tf/random/set_seed
# From practice, setting seeds causes it to shuffle in particular ways rather than randomly, except when only operational seed is chosen
# Global seems to force it to stay in one particular order

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>

### Other ways to make tensors

In [93]:
# tf.ones, creates tensor with all elements set to ones
tf.ones([10,7]) # give it a shape, 10x7 matrix

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [95]:
# tf.zeros, creates tensor with all elements set to zeros
tf.zeros(shape = (3,4)) # 3x4 matrix

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Turn NumPy arrays into tensors
The main diff between NumPy arrays and TF tensors is that tensors are run much faster on a GPU

In [98]:
# You can also turn NumPy arrays into tensors! (This means nothing to me) 
import numpy as np
numpy_A = np.arange(1,25,dtype=np.int32) # create a NumPy array between 1 and 25
numpy_A

# X = tf.constant(some_matrix) # Capital for matrix/tensor
# y = tf.constant(vector) # non capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [109]:
A = tf.constant(numpy_A, shape = (2,3,4)) # Converts NumPy array to tensor! Note 2*3*4 = 24, elements must add up to original array
B = tf.constant(numpy_A, shape = (3,8))
C = tf.constant(numpy_A)
A, B, C

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])>,
 <tf.Tensor: shape=(3, 8), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]])>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24])>)

### Getting information from Tensors
When dealing with tensors, be aware of the following attributes:
* Shape (tensor.shape)
* Rank (tensor.ndim)
* Axis/Dimension (tensor[0], tensor[:,1]...)
* Size (tf.size(tensor))

In [110]:
# Create a rank 4 tensor ( 4 dimensions)
rank_4_tensor = tf.zeros(shape = [2,3,4,5]) # 3 within the 2, 4 within the 3, 5 within the 4
# 2 for outermost layer, 3 within that layer, 4 rows, 5 columns in each
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [113]:
rank_4_tensor[0] # gives first set (out of 2 sets) of 3
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [117]:
# Get various attributes of our tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):" , rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along 0 axis:", rank_4_tensor.shape[0])
print("Elements along the last axis:", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor:", tf.size(rank_4_tensor))
print("Total number of elements in our tensor:", tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along 0 axis: 2
Elements along the last axis: 5
Total number of elements in our tensor: tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor: 120
